name: Python Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE: macos-x uses 10X the github CI minutes so be careful using that
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests/unit


  integration-tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE: macos-x uses 10X the github CI minutes so be careful using that
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ['3.9'] #, '3.10', '3.11']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Integration Tests
      run: |
        python -m unittest discover -s tests/integration